---
title: "Takım: Team B"
sidebar: false 
---

MUY665-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

1.  [Orkun AYDIN](/takim/orkun.qmd)

2.  [Mert CAGLAR](/takim/Mert_Caglar.qmd)

3.  [Oguzhan TURKYILMAZ](/takim/oguzhan.qmd)

4.  [Dicle BAYDAR](/takim/dicle.qmd)

5.  [Ayça YAVUZ](/takim/ayca.qmd)

6.  [Pınar KARABACAK](/takim/pinar.qmd)

7.  [Yasemin AKTAŞ](/takim/yasemin.qmd)

## Proje Adı

MUY660-İş Analitiği iyileştirme çalışmaları (örnek)

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
